title: Wentao's Blog
description: "This blog records Wentao Han's adventure in the world of hacking and so."
copyright: >
  &copy;2019 Wentao Han<br>
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/arp242/hello-css">Hello, CSS!</a> theme
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
nav:
  - index.html
  - posts.html
  - categories.html
  - tags.html
  - about.md
